<?xml version="1.0" encoding="utf-8"?>
<Database Name="OBTRS_DB" Class="db_OBTRSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VUTUANMINH-PC\SQLEXPRESS2005;Initial Catalog=OBTRS_DB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OBTRS_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_CompanyInfo" Member="tbl_CompanyInfos">
    <Type Name="tbl_CompanyInfo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AboutUs" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContactUs" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TermAndCondition" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PrivacyPolicy" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Roles" Member="tbl_Roles">
    <Type Name="tbl_Role">
      <Column Name="Role_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Role_Alias" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Role_tbl_Administrator" Member="tbl_Administrators" ThisKey="Role_ID" OtherKey="Admin_RoleID" Type="tbl_Administrator" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Administrator" Member="tbl_Administrators">
    <Type Name="tbl_Administrator">
      <Column Name="Admin_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Admin_RoleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Admin_Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_PasswordQuestion" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Admin_CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Admin_Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Admin_Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Admin_LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Admin_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Role_tbl_Administrator" Member="tbl_Role" ThisKey="Admin_RoleID" OtherKey="Role_ID" Type="tbl_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Services" Member="tbl_Services">
    <Type Name="tbl_Service">
      <Column Name="Services_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Services_Title" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Services_Release" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Services_Edit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Services_Content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Services_Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Services_ReadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Services_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_News" Member="tbl_News">
    <Type Name="tbl_New">
      <Column Name="News_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="News_Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="News_Release" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="News_Edit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="News_Content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="News_Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="News_ReadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="News_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_AccountCustomer" Member="tbl_AccountCustomers">
    <Type Name="tbl_AccountCustomer">
      <Column Name="AccountCustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountCustomer_Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AccountCustomer_Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AccountCustomer_IDNumber" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="AccountCustomer_FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AccountCustomer_Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccountCustomer_Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccountCustomer_Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountCustomer_PhoneNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AccountCustomer_Job" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_SearchNews" Method="sp_SearchNews">
    <Parameter Name="title" Type="System.String" DbType="NText" />
    <ElementType Name="sp_SearchNewsResult">
      <Column Name="News_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="News_Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="News_Release" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="News_Edit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="News_Content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="News_Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="News_ReadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="News_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchService" Method="sp_SearchService">
    <Parameter Name="title" Type="System.String" DbType="NText" />
    <ElementType Name="sp_SearchServiceResult">
      <Column Name="Services_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Services_Title" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Services_Release" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Services_Edit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Services_Content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Services_Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Services_ReadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Services_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetAdmin" Method="sp_GetAdmin">
    <ElementType Name="sp_GetAdminResult">
      <Column Name="Admin_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Role_Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Admin_Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>